In [ ]:
!pip install gokinjo

Collecting gokinjo
  Downloading gokinjo-0.1.0-py3-none-any.whl (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from gokinjo) (1.22.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from gokinjo) (1.2.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->gokinjo) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->gokinjo) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->gokinjo) (3.1.0)
Installing collected packages: gokinjo
Successfully installed gokinjo-0.1.0

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

from gokinjo import knn_kfold_extract
from gokinjo import knn_extract

# list all files under the input directory
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
!unzip -q /content/drive/MyDrive/tabular-playground-series-jun-2021.zip

In [ ]:
df_train = pd.read_csv('/content/train.csv')
df_test = pd.read_csv('/content/test.csv')

# label encode the target column
le = LabelEncoder()
df_train.target = le.fit_transform(df_train.target)

# define X and y for training data
X = df_train.drop(columns=["id","target"])
y = df_train.target

# prepare test data
X_test=df_test.drop(columns="id")

print("First five rows of training data:")
display(X.head())
print("First five rows of test data:")
display(X_test.head())

First five rows of training data:

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74
0,0,0,6,1,0,0,0,0,7,0,...,3,0,0,0,0,0,0,2,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,1,0
2,0,0,0,0,0,1,0,3,0,0,...,8,0,0,0,0,1,0,0,0,0
3,0,0,7,0,1,5,2,2,0,1,...,0,0,4,0,2,2,0,4,3,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

First five rows of test data:

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,0,0,0,0,0,0,0,0,...,3,1,3,0,0,0,0,3,0,0
2,0,1,7,1,0,0,0,0,6,0,...,3,0,0,0,0,3,0,2,0,0
3,0,0,0,4,3,1,0,0,0,0,...,0,0,0,1,0,0,0,4,0,0
4,0,0,5,0,0,0,0,0,0,8,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
X = X.to_numpy()
y = y.to_numpy()
X_test = X_test.to_numpy()
# check shapes
print("X, shape: ", np.shape(X))
print("X_test, shape: ", np.shape(X_test))

X, shape:  (200000, 75)
X_test, shape:  (100000, 75)

In [ ]:
KNN_feat_train = knn_kfold_extract(X, y, k=1, normalize='standard')
print("KNN features for training set, shape: ", np.shape(KNN_feat_train))
KNN_feat_train[0]

KNN features for training set, shape:  (200000, 9)

array([3.73803824, 3.46325028, 3.73321117, 3.57034447, 3.64955778,
       2.83328309, 3.32516955, 3.28908893, 3.12661974])

In [ ]:
KNN_feat_test = knn_extract(X, y, X_test, k=1, normalize='standard')
print("KNN features for test set, shape: ", np.shape(KNN_feat_test))

KNN features for test set, shape:  (100000, 9)

In [ ]:
X, X_test = np.append(X, KNN_feat_train, axis=1), np.append(X_test, KNN_feat_test, axis=1)
print("Train set, shape: ", np.shape(X))
print("Test set, shape: ", np.shape(X_test))

In [ ]:
np.save('add_feat_train', KNN_feat_train)
np.save('add_feat_test', KNN_feat_test)